version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: aalves/api-clients-version:2.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@client_db:5432/postgres
    depends_on:
    - client_db
    dns:
    - 8.8.8.8
    - 8.8.4.4
  client_db:
    container_name: client_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}